
spring:
  jpa:
    show-sql: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://188.131.252.174:3306/seacms?characterEncoding=utf8&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    hikari:.connectionTestQuery: SELECT 1
    hikari:.connectionTimeout: 30000
    hikari:.idleTimeout: 600000
    hikari:.maximum-pool-size: 80
    hikari:.maxLifetime: 18000000
    hikari:.minimum-idle: 5
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
    validation-query: SELECT 1
    test-on-borrow: false
    test-while-idle: true
    time-between-eviction-runs-millis: 18000

    ##默认密码为空
  redis:
        host: 188.131.252.174
        # Redis服务器连接端口
        port: 6379
        jedis:
          pool:
            #连接池最大连接数（使用负值表示没有限制）
            max-active: 100
            # 连接池中的最小空闲连接
            max-idle: 10
            # 连接池最大阻塞等待时间（使用负值表示没有限制）
            max-wait: 10000
        # 连接超时时间（毫秒）
            timeout: 1000
        #默认是索引为0的数据库
            database: 0



mybatis:
  typeAliasesPackage: com.site.vs.videostation.entity
  mapperLocations: classpath:mapper/*.xml

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

logging:
  level:
    com.site.vs.videostation.mapper: trace



