
spring:
  jpa:
    show-sql: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: mysql1901228385
    password: 8K38540be6
    url: jdbc:mysql://43.226.44.139:3306/mysql1901228385_db?characterEncoding=utf-8&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC


